### PR TITLE
lxd: fix network ip parsing

### PR DESCRIPTION
**Pull request by aciba90**

### CODE REVIEW

**Comment by aciba90** [comment]
Discovered here: https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-lunar-lxd_vm/lastCompletedBuild/testReport/tests.integration_tests.modules/test_version_change/test_log_message_on_missing_version_file_2/

**Comment by holmanb** [comment]
> Discovered here: https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-lunar-lxd_vm/lastCompletedBuild/testReport/tests.integration_tests.modules/test_version_change/test_log_message_on_missing_version_file_2/

At a quick glance, I'm not seeing how this lxd/zfs error relates to IP parsing. Did you mean to link a different issue?

**Comment by aciba90** [comment]
> > Discovered here: https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-lunar-lxd_vm/lastCompletedBuild/testReport/tests.integration_tests.modules/test_version_change/test_log_message_on_missing_version_file_2/
> 
> At a quick glance, I'm not seeing how this lxd/zfs error relates to IP parsing. Did you mean to link a different issue?

My bad, the correct one is: https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-lunar-lxd_vm/7/testReport/junit/tests.integration_tests.modules/test_user_events/test_boot_event_disabled_by_default_2/

**Review by holmanb — APPROVED** [review]
> My bad, the correct one is: https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-lunar-lxd_vm/7/testReport/junit/tests.integration_tests.modules/test_user_events/test_boot_event_disabled_by_default_2/

No problem. Thanks!

I tend to prefer this approach, for brevity:
```python
network = query.get("state", {}).get("network") or {}
```
That said, I'm not going to block this on preference.

LGTM, thanks for the fix!

**Pull request merged**
