### PR TITLE
fix(gce): GCE cloud launch correctly adds kwargs to the config

### PR DESCRIPTION
**Pull request by mstpn**
The function signature for the launch() function indicates that kwargs are added to the instance JSON, presumably through the config MutableMapping. However, this functionality was never implemented. An integration test for GCE was added to ensure this change is covered.

Fixes: [#384](https://github.com/canonical/pycloudlib/issues/384)

### CODE REVIEW

**Comment by a-dubs** [comment]
Great catch, @mstpn. And thanks for adding an integration test for ensuring this functionality works and will continue to work into the future :blue_heart:

**Review by a-dubs — COMMENTED** [review]
Great catch, @mstpn. And thanks for adding an integration test for ensuring this functionality works and will continue to work into the future :blue_heart:

Also, might I ask why the `.python-version` file has been deleted?

**Comment by TheRealFalcon** [comment]
> Also, might I ask why the .python-version file has been deleted?

We shouldn't remove it, but it should go in .gitignore.

**Comment by mstpn** [comment]
> > Also, might I ask why the .python-version file has been deleted?
> 
> We shouldn't remove it, but it should go in .gitignore.

Not sure how my removal managed to sneak in to the commit. I had issues with my pyvenv so I removed the file, but as you say, it is in the .gitignore. Restoring the file.

**Review by a-dubs — APPROVED** [review]
Nice work!

**Review by TheRealFalcon — COMMENTED** [review]
LGTM!

**Review by TheRealFalcon — APPROVED** [review]
...let's see if I can click the right button :man_facepalming:

**Pull request merged**
