### PR TITLE
pep517 compatible and static pkg definition (SC-1462)

### PR DESCRIPTION
**Pull request by aciba90**
## Proposed Commit Message

```
pep517 compatible and static pkg definition
```

## Additional Context

https://warthogs.atlassian.net/browse/SC-1462

## Test Steps

```
python -m build
python -m pip install -U ./dist/pycloudlib-*.whl
python -m pip install -U ./dist/pycloudlib-*.whl
```

## Checklist:

 - [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/contributing.html)
 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any documentation accordingly

### CODE REVIEW

**Comment by aciba90** [comment]
I have corrected this PR to add minimal support for pep517 mimicking https://github.com/canonical/cloud-init/commit/8836c7824533025768ec82c350a965b76a744b1e.

**Comment by TheRealFalcon** [comment]
@aciba90 do you still have the old commit? It's more complicated in cloud-init because of all of the Ubuntu versions we're supporting, but pushing project metadata into a declarative file (i.e., [pep 621](https://peps.python.org/pep-0621/)) is where things are going in python, and switching now wouldn't be a bad thing (but also not required)

**Comment by aciba90** [comment]
@TheRealFalcon let me try to rescue it!

**Comment by aciba90** [comment]
@TheRealFalcon recovered.

**Review by TheRealFalcon — APPROVED** [review]
LGTM!

**Pull request merged**
