### PR TITLE
update tox.ini (SC-674)

### PR DESCRIPTION
**Pull request by TheRealFalcon**
Includes:
* Docs build
* Share testenvs when reasonable
* Share common config when reasonable
* Bump linting versions
* Rename py3 env to pytest
* Remove nose section
* Remove default recreate=true

Also update main makefile clean to also clean docs dir and print docs
make commands to stdout.

### CODE REVIEW

**Comment by paride** [comment]
All nice changes, thanks! I can't spot right away why tox itself is failing in CI. Maybe Bionic's tox is too old? The rationale for testing in Bionic is that it's the oldest Ubuntu release we can reasonably want to use pycloudlib on.)

**Comment by paride** [comment]
I can reproduce the failure on Bionic.

**Comment by TheRealFalcon** [comment]
Yeah, looks like the bionic version uses a tox from 2015 :astonished: . Since we don't package pycloudlib into any OS repos, I think I'm ok using the pip version of tox here. I'm going to play with that unless you think we shoudln't.

**Review by paride — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
