### PR TITLE
azure: integrate azure-cli-core new API

### PR DESCRIPTION
**Pull request by aciba90**
azure: integrate azure-cli-core new API

### CODE REVIEW

**Comment by aciba90** [comment]
Migration info:

* [authenticating-through-the-azure-cli](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/migration_guide.md#authenticating-through-the-azure-cli)
* [asynchronous-operations](https://docs.microsoft.com/en-us/azure/developer/python/sdk/azure-sdk-library-usage-patterns?tabs=pip#asynchronous-operations)

**Comment by aciba90** [comment]
Reopen to trigger the build.

**Review by holmanb — APPROVED** [review]
I think this change is actually required to use current versions of azure cli. I bumped into this issue previously during cloud-init integration testing. Without this change commit I get the "please run `az login`" message over and over (even though I _have_ logged in).

Thanks!

**Comment by hammerstefan** [comment]
This change allows tools using `pycloulib` to use newer `azure-mgmt-*` libraries, which is required to use any of the functionality added to those libraries in the past two years.  This gets a big :+1: from me.

**Pull request merged**
