### PR TITLE
Add missing `noble` image strings on Azure

### PR DESCRIPTION
**Pull request by renanrodrigo**
This changeset adds three new entries for the dictionaries which point to the Azure images to be launched by pycloudlib, all of them `noble`:
- the 24.04 Pro image
- the 24.04 released server image
- the 24.04 CVM image

Fixes: GH-376

### CODE REVIEW

**Comment by renanrodrigo** [comment]
Hmmmm sorry not incrementing the version - not sure how the process works nowadays, specially release-wise.
Should I just bump it?

**Review by aciba90 — APPROVED** [review]
LGTM, thanks!

Yes, just bump the VERSION file, minor release I guess.

Fyi: There is a [version_check](https://github.com/canonical/pycloudlib/blob/main/.github/workflows/version_check.py) and a post-merge [tag and release](https://github.com/canonical/pycloudlib/blob/main/.github/workflows/tag_and_publish.yaml) action.

**Comment by renanrodrigo** [comment]
@aciba90 thanks for the pointer!
All done

**Comment by renanrodrigo** [comment]
Is it though?
I mean, the functionality itself is there, we are just adding more options to it, adding the missing bits.
But it's your call - done it!

**Comment by aciba90** [comment]
Good point. From a consumer perspective, pycloudlib is adding support for looking up noble images. IMO, that's a new feature/. But I agree, from a dev POV this is trivial.

**Review by aciba90 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
